### ISSUE TITLE
pandoc breaking change

### ISSUE THREAD

**Issue by mralbu** [HaoLiuHust/mkdocs-mk2pdf-plugin#4]
pandoc realeased a breaking change in 2017: [Rename --latex-engine to --pdf-engine, and --latex-engine-opt to --pdf-engine-opt.](https://pandoc.org/releases.html)

I managed to fix the error I was getting about this breaking change, altering mk2pdf-plugin's renderer.py

```python
def write_pdf(self,  mk_filename: str, pdf_filename: str):
        if os.path.isfile(self.template) and os.path.exists(self.template):
            os.system('pandoc --pdf-engine=xelatex --template=%s  %s -o %s'%(self.template,mk_filename,pdf_filename))
        else:
            os.system('pandoc --pdf-engine=xelatex %s -o %s'%(mk_filename,pdf_filename))
```

**Comment by HaoLiuHust** [comment]
maybe you can propose a merge request

**Comment by mralbu** [comment]
Sure, thank you!
